[package]
name = "gorget"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "gg"
path = "src/main.rs"

[dependencies]
logos = "0.15"
codespan-reporting = "0.11"
rustc-hash = "2.0"
serde_json = "1"

[dev-dependencies]
insta = "1"
pretty_assertions = "1"
